/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'davicres' at '31/03/16 19:29' with Gradle 2.12
 *
 * @author davicres, @date 31/03/16 19:29
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
