/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'davicres' at '3/31/16 2:23 PM' with Gradle 2.12
 *
 * @author davicres, @date 3/31/16 2:23 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
